/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.vosk;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.text.DefaultCaret;

/**
 *
 * @author Toshiba
 */
public class OverlayWindow extends javax.swing.JFrame {

    public OverlayWindow() {

        setUndecorated(true);
        initComponents();

        Dimension screenSize,frameSize;
        int x,y;
        screenSize=Toolkit.getDefaultToolkit().getScreenSize();
        DISPLAY.WIDTH = screenSize.width;
        DISPLAY.HEIGHT = screenSize.height;
        setSize((int) (0.75*DISPLAY.WIDTH), (int) (0.06*DISPLAY.HEIGHT));
        frameSize=getSize();
        x = (int) ((screenSize.width-frameSize.width)/2);
        y = (int) (0.8*(screenSize.height-frameSize.height));
        setLocation(x, y);

        DefaultCaret caret = (DefaultCaret)overlay_textpane_translation_text.getCaret();
        caret.setUpdatePolicy(DefaultCaret.OUT_BOTTOM);
        caret.setUpdatePolicy(DefaultCaret.ALWAYS_UPDATE);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        overlay_textpane_translation_text = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new Color(0, 0, 0, 0));
        setUndecorated(true);
        setSize(new java.awt.Dimension(0, 0));

        overlay_textpane_translation_text.setBackground(new Color(0,0,0,0));
        overlay_textpane_translation_text.setColumns(20);
        overlay_textpane_translation_text.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        overlay_textpane_translation_text.setForeground(new Color(187,187,0,255));
        overlay_textpane_translation_text.setLineWrap(true);
        overlay_textpane_translation_text.setRows(2);
        overlay_textpane_translation_text.setWrapStyleWord(true);
        overlay_textpane_translation_text.setBorder(javax.swing.BorderFactory.createEmptyBorder());
        overlay_textpane_translation_text.setSelectedTextColor(new Color(187,187,0,255));
        overlay_textpane_translation_text.setSelectionColor(new Color(0,0,0,160));
        overlay_textpane_translation_text.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                overlay_textpane_translation_textMouseDragged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(overlay_textpane_translation_text)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(overlay_textpane_translation_text, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void overlay_textpane_translation_textMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_overlay_textpane_translation_textMouseDragged
        int x = (int) (evt.getXOnScreen() - 0.5*getWidth());
        int y = (int) (evt.getYOnScreen() - 0.5*getHeight());
        setLocation(x, y);
    }//GEN-LAST:event_overlay_textpane_translation_textMouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OverlayWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OverlayWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextArea overlay_textpane_translation_text;
    // End of variables declaration//GEN-END:variables
}
