/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.vosk;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;
import java.awt.Toolkit;
import javax.swing.text.DefaultCaret;

/**
 *
 * @author Toshiba
 */
public class OverlayTranslationWindow extends javax.swing.JFrame {

    public OverlayTranslationWindow() {

        GraphicsDevice gd = GraphicsEnvironment.getLocalGraphicsEnvironment().getDefaultScreenDevice();
        DISPLAY.WIDTH = gd.getDisplayMode().getWidth();
        DISPLAY.HEIGHT = gd.getDisplayMode().getHeight();

        setUndecorated(true);
        initComponents();

        Dimension screenSize,frameSize;
        int x,y;
        screenSize=Toolkit.getDefaultToolkit().getScreenSize();
        frameSize=getSize();
        x = (int) ((screenSize.width-frameSize.width)/2);
        y = (int) (0.8*(screenSize.height-frameSize.height));
        setLocation(x, y);

        DefaultCaret caret = (DefaultCaret)textpane_translation_text.getCaret();
        caret.setUpdatePolicy(DefaultCaret.OUT_BOTTOM);
        caret.setUpdatePolicy(DefaultCaret.ALWAYS_UPDATE);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        textpane_translation_text = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new Color(0, 0, 0, 1));
        setForeground(new Color(0, 0, 0, 0));
        setUndecorated(true);
        setSize((int) (0.75*DISPLAY.WIDTH), (int) (0.09*DISPLAY.HEIGHT));

        jScrollPane1.setBackground(new Color(0, 0, 0, 0));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder());
        jScrollPane1.setForeground(new Color(0, 0, 0, 0));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        textpane_translation_text.setEditable(false);
        textpane_translation_text.setBackground(new Color(0, 0, 0, 0));
        textpane_translation_text.setBorder(javax.swing.BorderFactory.createEmptyBorder());
        textpane_translation_text.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        textpane_translation_text.setForeground(new java.awt.Color(255, 255, 0));
        textpane_translation_text.setSelectedTextColor(new java.awt.Color(255, 255, 0));
        textpane_translation_text.setSelectionColor(new Color(0,0,0,255));
        textpane_translation_text.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                textpane_translation_textMouseDragged(evt);
            }
        });
        jScrollPane1.setViewportView(textpane_translation_text);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1012, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void textpane_translation_textMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textpane_translation_textMouseDragged
        int x = (int) (evt.getXOnScreen() - 0.5*this.getWidth());
        int y = (int) (evt.getYOnScreen() - 0.5*this.getHeight());
        this.setLocation(x, y);
    }//GEN-LAST:event_textpane_translation_textMouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OverlayTranslationWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OverlayTranslationWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextPane textpane_translation_text;
    // End of variables declaration//GEN-END:variables
}
